### ISSUE TITLE
Scoped API broken

### ISSUE THREAD

**Issue by Casper-Mars** [auth0-samples/auth0-golang-api-samples#36]
`json: cannot unmarshal string into Go struct field CustomClaims.aud of type []string` due to this https://github.com/auth0-samples/auth0-golang-api-samples/blob/95f924a83f91eab901c4e1cb1b708980ac507a80/01-Authorization-RS256/main.go#L126
 The token I got just contain a single audience string. But audience should be array as describe at [rfc](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3)

**Comment by sergiughf** [comment]
This issue was fixed in https://github.com/auth0-samples/auth0-golang-api-samples/pull/39

We really appreciate you taking the time to report this @Casper-Mars ! Please let us know if there are any other issues!
